ZSH=$HOME/.oh-my-zsh
ZSH_THEME="kphoen"

plugins=(git)

source $ZSH/oh-my-zsh.sh
source $HOME/.vagrant.sh

export PATH=/usr/local/share/python:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

PATH=$PATH:$HOME/.rvm/bin
